# Generated by Django 5.2.7 on 2025-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSaasTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Configuración')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('estado', models.CharField(choices=[('en_prueba', 'En Prueba'), ('activo', 'Activo'), ('cancelado', 'Cancelado')], default='en_prueba', max_length=20, verbose_name='Estado SaaS')),
                ('fecha_vencimiento_prueba', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vencimiento de Prueba')),
            ],
            options={
                'verbose_name': 'Estado SaaS del Tenant',
                'verbose_name_plural': 'Estados SaaS del Tenant',
            },
        ),
        migrations.CreateModel(
            name='PlanTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Configuración')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('tipo_plan', models.CharField(choices=[('gratis', 'Gratis'), ('basico', 'Básico'), ('profesional', 'Profesional')], default='gratis', max_length=20, verbose_name='Tipo de Plan')),
                ('limite_usuarios', models.IntegerField(default=5, verbose_name='Límite de Usuarios')),
                ('limite_creditos', models.IntegerField(default=10, verbose_name='Límite de Créditos Mensuales')),
            ],
            options={
                'verbose_name': 'Plan del Tenant',
                'verbose_name_plural': 'Planes del Tenant',
            },
        ),
        migrations.CreateModel(
            name='TemaTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Configuración')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('tema', models.CharField(choices=[('automatico', 'Automático'), ('oscuro', 'Oscuro'), ('claro', 'Claro')], default='automatico', max_length=20, verbose_name='Tema')),
                ('color_primario', models.CharField(default='#3498db', max_length=7, verbose_name='Color Primario (HEX)')),
                ('color_secundario', models.CharField(default='#2c3e50', max_length=7, verbose_name='Color Secundario (HEX)')),
            ],
            options={
                'verbose_name': 'Tema del Tenant',
                'verbose_name_plural': 'Temas del Tenant',
            },
        ),
    ]
