# Generated by Django 5.2.6 on 2025-10-15 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_Institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoSuscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(verbose_name='Fecha de Pago')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('tiempo_cubierto', models.IntegerField(verbose_name='Tiempo Cubierto')),
                ('id_transaccion_externo', models.CharField(max_length=100, unique=True, verbose_name='ID Transacción Externo')),
                ('instituto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_suscripcion', to='shared_Institucion.instituto', verbose_name='Instituto')),
            ],
            options={
                'verbose_name': 'Pago de Suscripción',
                'verbose_name_plural': 'Pagos de Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='AppSuscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum_plan', models.CharField(choices=[('gratis', 'Gratis'), ('basico', 'Básico'), ('profesional', 'Profesional')], default='gratis', max_length=20, verbose_name='Plan')),
                ('enum_estado_saas', models.CharField(choices=[('en_prueba', 'En Prueba'), ('activo', 'Activo'), ('cancelado', 'Cancelado')], default='en_prueba', max_length=20, verbose_name='Estado SaaS')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_final', models.DateTimeField(verbose_name='Fecha Final')),
                ('pago_suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_contratadas', to='shared_Pagos.pagosuscripciones', verbose_name='Pago de Suscripción')),
            ],
            options={
                'verbose_name': 'App de Suscripción',
                'verbose_name_plural': 'Apps de Suscripciones',
            },
        ),
    ]
