# Generated by Django 5.2.7 on 2025-10-15 17:10

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('numero_contacto', models.CharField(max_length=20, verbose_name='Número de Contacto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Instituto')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='URL del Logo')),
            ],
            options={
                'verbose_name': 'Instituto Financiero',
                'verbose_name_plural': 'Institutos Financieros',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='shared_Institucion.instituto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
