# Generated by Django 5.2.7 on 2025-10-15 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Color en formato HEX (ej: #3498db)', max_length=7, verbose_name='Color')),
                ('tipos_letra', models.CharField(max_length=50, verbose_name='Tipos de Letra')),
                ('enum_tema', models.CharField(choices=[('automatico', 'Automático'), ('oscuro', 'Oscuro'), ('claro', 'Claro')], default='automatico', max_length=20, verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Configuración Custom',
                'verbose_name_plural': 'Configuraciones Custom',
            },
        ),
        migrations.CreateModel(
            name='AppCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil_url', models.URLField(blank=True, null=True, verbose_name='Foto de Perfil URL')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='tenat_Django_users.custom', verbose_name='Configuración Custom')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario Custom',
                'verbose_name_plural': 'Perfiles de Usuarios Custom',
            },
        ),
    ]
